-- -- Bindings for vs-tasks
-- vim.keymap.set('n', '<Leader>ta', function() require('telescope').extensions.vstask.tasks() end, {})
-- vim.keymap.set('n', '<Leader>ti', function() require('telescope').extensions.vstask.inputs() end, {})
-- vim.keymap.set('n', '<Leader>th', function() require('telescope').extensions.vstask.history() end, {})
-- vim.keymap.set('n', '<Leader>tl', function() require('telescope').extensions.vstask.launch() end, {})
-- require('vstask').setup {
--   autodetect = {
--     npm = 'on'
--   },
--   telescope_keys = {
--     vertical = "<C-v>",
--     split = "<CR>",
--     tab = "<C-t>",
--   },
--   terminal = 'toggleterm',
-- }
-- 
-- 
-- -- DAP
-- local dap = require('dap')
-- dap.adapters.python = {
--   type = 'executable',
--   command = home .. '/.virtualenvs/debugpy/bin/python',
--   args = { '-m', 'debugpy.adapter' }
-- }
-- 
-- dap.configurations.python = {
--   {
--     -- The first three options are required by nvim-dap
--     type = 'python'; -- the type here established the link to the adapter definition: `dap.adapters.python`
--     request = 'launch';
--     name = "Launch file";
-- 
--     -- Options below are for debugpy, see https://github.com/microsoft/debugpy/wiki/Debug-configuration-settings for supported options
--     program = "${file}"; -- This configuration will launch the current file if used.
--     pythonPath = function()
--       -- debugpy supports launching an application with a different interpreter then the one used to launch debugpy itself.
--       -- The code below looks for a `venv` or `.venv` folder in the current directly and uses the python within.
--       -- You could adapt this - to for example use the `VIRTUAL_ENV` environment variable.
--       local cwd = vim.fn.getcwd()
--       if vim.fn.executable(cwd .. '/venv/bin/python') == 1 then
--         return cwd .. '/venv/bin/python'
--       elseif vim.fn.executable(cwd .. '/.venv/bin/python') == 1 then
--         return cwd .. '/.venv/bin/python'
--       else
--         return '/usr/bin/python'
--       end
--     end;
--   }
-- }
-- 
-- 
-- vim.keymap.set('n', '<Leader>db', function () require('dap').toggle_breakpoint() end, {})
-- vim.keymap.set('n', '<Leader>dc', function () require('dap').continue() end, {})
-- vim.keymap.set('n', '<Leader>dso', function () require('dap').step_over() end, {})
-- vim.keymap.set('n', '<Leader>dsi', function () require('dap').step_into() end, {})
-- vim.keymap.set('n', '<Leader>dr', function () require('dap').repl.open() end, {})
-- 
-- vim.keymap.set('n', '<F5>', function () require('dap').continue() end, {})
-- vim.keymap.set('n', '<F6>', function () require('dap').step_over() end, {})
-- 
-- 
